name: Compilar proyecto C# (.NET 8)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Instalar .NET 8
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar solución
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar programa con entrada automática
      run: |
        printf "28\n2\n2024\n" | dotnet run --project Ejer17Consola/Ejer17Consola.csproj
  
    - name: Ejecutar programa con entrada automática
      run: |
        printf "28\n2\n2024\n" | dotnet run --project Ejer17Consola/Ejer17Consola.csproj

    - name: Ejecutar programa con entrada automática
      run: |
        printf "29\n2\n2024\n" | dotnet run --project Ejer17Consola/Ejer17Consola.csproj

    - name: Ejecutar programa con entrada automática
      run: |
        printf "31\n12\n2024\n" | dotnet run --project Ejer17Consola/Ejer17Consola.csproj

    - name: Ejecutar programa con entrada automática
      run: |
        printf "30\n4\n2024\n" | dotnet run --project Ejer17Consola/Ejer17Consola.csproj

